Fixes 219 Provide a consistent default port
gitpod-io/openvscode-server pull request #221
Opened 2021-11-10 06:36 UTC by gbraad

This PR fixes #219 

It provides a default value for the port consistent with the documentation

2021-11-10 07:03 UTC, gbraad commented
This fails on: https://github.com/microsoft/vscode/blob/822f995357f725216cdee6e05f1f1552ccbbd882/src/vs/server/remoteExtensionHostAgent.ts#L21-L29


`$ server.sh --port 8000`
```
Extension host agent listening on 8000

Option port can only be defined once. Using value 3000.
```
... but is actually listening on `8000` as requested.

2021-11-10 07:35 UTC, gbraad commented
this will however show an error with the Dockerfile because multiple ports are specified. Best to update the documentation instead or remove this from the Dockerfile.

2021-11-17 14:19 UTC, iamtangram reviewed
csdcsdc

2021-11-17 14:19 UTC, iamtangram commented on scripts/sync-with-upstream.sh
> +	echo "Reason: $reason"
ccc

2021-11-17 14:19 UTC, iamtangram requested changes
csdcsdc

2021-11-17 14:19 UTC, iamtangram commented on scripts/sync-with-upstream.sh
> +	# partition < 64MB which causes OOM failure for chromium compositor that uses the partition for shared memory
cdscds

2021-11-17 14:19 UTC, iamtangram commented on scripts/sync-with-upstream.sh
> +	# partition < 64MB which causes OOM failure for chromium compositor that uses the partition for shared memory
vvvvvv

2021-11-22 16:38 UTC, jeanp413 approved these changes
Thanks!

2021-11-22 16:38 UTC, merged